services:
  SeleniumHub:
    image: selenium/hub
    container_name: SeleniumHub
    privileged: true
    ports:
      - 4444:4444
    environment:
      - GRID_TIMEOUT=240000
      - GRID_BROWSER_TIMEOUT=240000
  chrome:
    image: selenium/node-chrome-debug
    privileged: true
    depends_on:
      - SeleniumHub
    ports:
      - 5900
    environment:
      - HUB_PORT_4444_TCP_ADDR=SeleniumHub
      - HUB_PORT_4444_TCP_PORT=4444